In [201]:
# Tuples
# import sys
# sys.path
# kernel.json
# from jupyter_core.paths import jupyter_data_dir
# print(jupyter_data_dir())
# sudo pip install --upgrade ipykernel
# source activate ipykernel_py3
# jupyter kernelspec list
import pandas as pd
# !pip install pandas
# jupyter kernelspec list

In [202]:
tup = ((1,2,3),(4,5,6),(7,8,9))

In [203]:
for a,b,c in tup:
    print(a)
    print(b)
    print(c)

1
2
3
4
5
6
7
8
9


In [204]:
for a,b,c in tup:
    print('a={0},b={1},c={2}'.format(a,b,c))


a=1,b=2,c=3
a=4,b=5,c=6
a=7,b=8,c=9


In [205]:
tuplesss = ((1,2,3), 4, 5,(7,8))

In [206]:
for i in tuplesss:
    print(i)

(1, 2, 3)
4
5
(7, 8)


In [207]:
x,*y,z = ((1,2,3),4,5,(10,11),(6,7))
print(y)

[4, 5, (10, 11)]


In [208]:
a=(5,6)
b=(1,4)
if (a>b):print("a is bigger")
else: print("b is bigger")

a is bigger


In [209]:
tuplesss = ((1,2,3), 4, 5,(7,8))


In [210]:
import numpy as np


In [211]:
# List


In [12]:
a_list = [1, True,[a,b,'c']]

In [13]:
a_list[2]

[(5, 6), (1, 4), 'c']

In [14]:
a_list[2][2]

'c'

In [15]:
a_list.append('rangbaaz')

In [16]:
a_list


[1, True, [(5, 6), (1, 4), 'c'], 'rangbaaz']

In [17]:
a_list.remove(1)

In [18]:
a_list



[True, [(5, 6), (1, 4), 'c'], 'rangbaaz']

In [19]:
a_list.remove(a_list[1])
a_list

[True, 'rangbaaz']

In [20]:
a_list.pop(1)

'rangbaaz'

In [21]:
a_list


[True]

In [22]:
# Built-in Sequence Functions
# enumerate
# It’s common when iterating over a sequence to want to keep track of the index of the
# current item.


In [23]:
collection = [1,2,3,4,5]
i=0
for value in collection:
    i = i+1
    print(i)

1
2
3
4
5


In [24]:
for key, value in enumerate(collection):
    print (value)
    

1
2
3
4
5


In [25]:
# zip
# zip
# zip “pairs” up the elements of a number of lists, tuples, or other sequences to create a
# list of tuples

In [26]:
seq1= ['foo','bae', 'mona']
seq2= ['lenti','chutu','darling']

In [27]:
zipped = zip(seq1, seq2)

In [28]:
zipped

In [29]:
list(zipped)

[('foo', 'lenti'), ('bae', 'chutu'), ('mona', 'darling')]

In [30]:
seq1= ['foo','bae', 'mona']
seq2= ['lenti','chutu']

In [31]:
zipped = zip(seq1,seq2)

In [32]:
list(zipped)

[('foo', 'lenti'), ('bae', 'chutu')]

In [33]:
seq1= ['foo','bae', 'mona']
seq2= ['lenti','chutu']
seq3= [True, False]

In [34]:
zipped = zip(seq1,seq2,seq3)

In [35]:
list(zipped)

[('foo', 'lenti', True), ('bae', 'chutu', False)]

In [36]:
for key,(a,b) in enumerate(zip(seq1,seq2)):
    print('{0}: {1} & {2}'.format(key,a,b))

0: foo & lenti
1: bae & chutu


In [37]:
for key,(a,b,c) in zipped:
    print('{0}: {1} & {2} & {3}'.format(key,a,b,c))

In [38]:
for key,(a,b,c) in enumerate(zip(seq1,seq2,seq3)):
    print('{0}: {1} & {2} & {3}'.format(key,a,b,c))

0: foo & lenti & True
1: bae & chutu & False


In [39]:
# Dict
# dict is likely the most important built-in Python data structure. A more common
# name for it is hash map or associative array. It is a flexibly sized collection of key-value
# pairs, where key and value are Python objects. One approach for creating one is to use
# curly braces {} and colons to separate keys and values:

In [40]:
# empty_dicyt = {d1: '1',d2: '2'}

In [41]:
empty_dicyt = {'d1': 1,'d2': 2}

In [42]:
empty_dicyt[1]

KeyError: 1

In [43]:
empty_dicyt['d1']

1

In [44]:
empty_dicyt.keys()

dict_keys(['d1', 'd2'])

In [45]:
list(empty_dicyt.keys())

['d1', 'd2']

In [46]:
empty_dicyt.values()

dict_values([1, 2])

In [47]:
list(empty_dicyt.values())

[1, 2]

In [48]:
# Merge two dictionaries





In [49]:
empty_dicyt.update({'d3': 3,'d4':'4'})

In [50]:
list(empty_dicyt.values())

[1, 2, 3, '4']

In [51]:
list(empty_dicyt)

['d1', 'd2', 'd3', 'd4']

In [52]:
# Creating dicts from sequences


# Method 1

In [53]:
mapping = {}
keyList ={'a':1,'b':2}
valueList ={'c':3,'d':4}

for key,value in zip(keyList, valueList):
    mapping[key]=value
    

In [54]:
mapping

{'a': 'c', 'b': 'd'}

In [55]:
# Since a dict is essentially a collection of 2-tuples, the dict function accepts a list of
# 2-tuples



# Method 2

In [56]:
mapping = dict(zip(keyList, valueList))

In [57]:
mapping

{'a': 'c', 'b': 'd'}

mapping

In [58]:
mapping = dict(zip(reversed(range(5)), range(5)))

In [59]:
mapping

{4: 0, 3: 1, 2: 2, 1: 3, 0: 4}

In [60]:
# getting values







In [61]:
value = mapping.get(4)

In [62]:
value

0

In [63]:
# categorizing a list of words by their
# first letters as a dict of lists








In [64]:
words = ['apple','car','atom','break','dicck']
byLetter = {}

In [65]:
for word in words:
    letter = word[0]
    if letter not in byLetter:
        byLetter[letter]=[word]
    else:
        byLetter[letter].append(word)    

In [66]:
byLetter

{'a': ['apple', 'atom'], 'c': ['car'], 'b': ['break'], 'd': ['dicck']}

In [67]:
for word in words:
    letter = word[0]
    byLetter.setdefault(letter, []).append(word)

In [68]:
byLetter

{'a': ['apple', 'atom', 'apple', 'atom'],
 'c': ['car', 'car'],
 'b': ['break', 'break'],
 'd': ['dicck', 'dicck']}

In [69]:
from collections import defaultdict
by_letter = defaultdict(list)
for word in words:
    by_letter[word[0]].append(word)

In [70]:
by_letter

defaultdict(list,
            {'a': ['apple', 'atom'],
             'c': ['car'],
             'b': ['break'],
             'd': ['dicck']})

####
List, Set, and Dict Comprehensions
List comprehensions are one of the most-loved Python language features. They allow
you to concisely form a new list by filtering the elements of a collection, transforming
the elements passing the filter in one concise expression

####

# [expr for val in collection if condition]

Q. given a
list of strings, we could filter out strings with length 2 or less and also convert them to
uppercase

In [71]:
strings = ['a','ab','acd','fuckThisShit','I will do it, bitch', 'bitch Lasagna']

In [72]:
(x.upper() for x in strings if(len(x)>2))

<generator object <genexpr> at 0x7f9af7f56308>

In [73]:
print((x.upper() for x in strings if(len(x)>2)))

<generator object <genexpr> at 0x7f9af7f565c8>


In [74]:
strings


['a', 'ab', 'acd', 'fuckThisShit', 'I will do it, bitch', 'bitch Lasagna']

In [75]:
[x.upper() for x in strings if(len(x)>2)]


['ACD', 'FUCKTHISSHIT', 'I WILL DO IT, BITCH', 'BITCH LASAGNA']

In [76]:
strings1

NameError: name 'strings1' is not defined

In [77]:
strings

['a', 'ab', 'acd', 'fuckThisShit', 'I will do it, bitch', 'bitch Lasagna']

In [78]:
unique_len = {len(x) for x in strings}

In [79]:
unique_len

{1, 2, 3, 12, 13, 19}

In [80]:
unique_len = {x.upper() for x in strings if(len(x)>2)}

In [81]:
unique_len



{'ACD', 'BITCH LASAGNA', 'FUCKTHISSHIT', 'I WILL DO IT, BITCH'}

In [82]:
local_mapping = {value: index for index, value in enumerate(strings)}

Q.As a simple dict comprehension example, we could create a lookup map of these
strings to their locations in the list

In [83]:
local_mapping

{'a': 0,
 'ab': 1,
 'acd': 2,
 'fuckThisShit': 3,
 'I will do it, bitch': 4,
 'bitch Lasagna': 5}

In [84]:
all_data = [['John', 'Emily', 'Michael', 'Mary', 'Steven'],
['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]

Q. suppose we wanted to get a single list containing all names
with two or more e ’s in them.

In [85]:
result=[name for names in all_data for name in names if(name.count('e')>=2)]

In [86]:
result

['Steven']

In [87]:
some_tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [88]:
flattenedTup = [flat for tup in some_tuples for flat in tup]

In [89]:
flattenedTup

[1, 2, 3, 4, 5, 6, 7, 8, 9]

#Functions Are Objects


Since Python functions are objects, many constructs can be easily expressed that are
difficult to do in other languages. Suppose we were doing some data cleaning and
needed to apply a bunch of transformations to the following list of string

In [90]:
states = ['Alabama ', 'Georgia!', 'Georgia', 'georgia-- ', 'FlOrIda][]','"south carolina##"', 'West virginia?']

In [91]:
import re

In [92]:
result=[]
def clean_strings(strings):
    for value in strings:
        value=value.strip() #removes whitespaces from front and behind
        value=re.sub('[!#?"-]','', value) #first '[!#?"-]' is pattern, second is replacing the excluded pattern with nothing, third is the string we are passing
        value=value.title()
        result.append(value)
    return result

In [93]:
clean_strings(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida][]',
 'South Carolina',
 'West Virginia']

In [94]:
# Numpy


In [95]:
import numpy as np


In [96]:
np_array = np.arange(1000000)

In [97]:
my_lits = list(range(1000000))

In [98]:
%time 
for _ in range(10):
    np_array=np_array*2

CPU times: user 5 µs, sys: 2 µs, total: 7 µs
Wall time: 17.2 µs


In [99]:
%time
for _ in range(10):
    my_lits2= [x*2 for x in my_lits]

CPU times: user 6 µs, sys: 0 ns, total: 6 µs
Wall time: 14.5 µs


In [100]:
data = np.random.randn(2,3)

In [101]:
data

array([[-0.49846715,  0.7222814 ,  2.51111725],
       [-0.86555491,  1.54960963,  1.0318111 ]])

In [102]:
data = data*10


In [103]:
data

array([[ -4.98467151,   7.222814  ,  25.11117253],
       [ -8.65554914,  15.49609633,  10.31811103]])

In [104]:
data.shape

(2, 3)

In [105]:
data.dtype

dtype('float64')

In [106]:
data =  [1,2,13,3,5]

In [107]:
data= np.array(data)

In [108]:
data

array([ 1,  2, 13,  3,  5])

In [109]:
data.dtype

dtype('int64')

In [110]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [111]:
np.zeros((10))

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [112]:
np.zeros((10,))

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [113]:
arrayas = np.random.randn(2,3)

In [114]:
arrayas

array([[ 0.40765568, -0.26567251, -0.12165152],
       [ 0.53790477, -1.39388927,  0.36041803]])

In [115]:
data2 = [[1,2,3,4],[5,6,7],8]

In [116]:
arr2 = np.array(data2)

In [117]:
arr2


array([[1, 2, 3, 4], [5, 6, 7], 8], dtype=object)

In [118]:
arr2.ndim

1

In [119]:
arr2.shape

(3,)

In [120]:
arr2.dtype

dtype('O')

In [121]:
arr = np.array([[1,3,4],[5,6,8]])

In [122]:
arr.dtype

dtype('int64')

In [123]:
arr.astype(np.float64)

array([[ 1.,  3.,  4.],
       [ 5.,  6.,  8.]])

In [124]:
arr*arr


array([[ 1,  9, 16],
       [25, 36, 64]])

In [125]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [126]:
1/arr

array([[ 1.        ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.125     ]])

In [127]:
arr*2

array([[ 2,  6,  8],
       [10, 12, 16]])

In [128]:
arr2 = np.array([[7,1,9],[2,3,4]])

In [129]:
arr>arr2

array([[False,  True, False],
       [ True,  True,  True]], dtype=bool)

# Basic indexing and slicing

In [130]:
arr = np.arange(10)

In [131]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
arr[5:8:2]

array([5, 7])

In [133]:
arr[5:8]

array([5, 6, 7])

In [134]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [135]:
arr2d[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [136]:
arr2d[0]

array([1, 2, 3])

In [137]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12],[13,14,15]]])

In [138]:
arr3d.shape

(2,)

In [139]:
arr3d[0]

[[1, 2, 3], [4, 5, 6]]

In [140]:
arr3d[1]

[[7, 8, 9], [10, 11, 12], [13, 14, 15]]

In [141]:
arr3d[1][0]

[7, 8, 9]

In [142]:
arr3d[0]=45

In [143]:
arr3d.shape

(2,)

In [144]:
arr3d[0]

45

In [145]:
arr3d[1]

[[7, 8, 9], [10, 11, 12], [13, 14, 15]]

In [146]:
arr3d

array([45, [[7, 8, 9], [10, 11, 12], [13, 14, 15]]], dtype=object)

In [147]:
arr3d[1][0]

[7, 8, 9]

In [148]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [149]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [150]:
arr2d[:1]

array([[1, 2, 3]])

In [151]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [152]:
arr2d[2:,:1]

array([[7]])

# Boolean Indexing

In [153]:
names = np.array(['bob','sob','leela','majnu','apsara','ross','leo'])

In [154]:
data = np.random.randn(7,4)

In [155]:
data


array([[-0.97008236,  0.86985823,  0.10699726, -0.89757453],
       [ 1.17469316, -0.15631129, -0.47882262, -0.48743776],
       [ 1.86861288,  1.37530394,  0.30821481, -0.62066787],
       [ 0.10844734,  0.57141365,  1.596644  ,  1.7138495 ],
       [ 1.01203413, -0.12030664, -1.11519312,  0.33520322],
       [-1.02232956,  0.60114853, -1.2055723 , -0.00310021],
       [ 0.94850782,  1.59295635, -1.58483102,  0.31055118]])

In [156]:
names

array(['bob', 'sob', 'leela', 'majnu', 'apsara', 'ross', 'leo'], 
      dtype='<U6')

In [157]:
names == 'bob'

array([ True, False, False, False, False, False, False], dtype=bool)

In [158]:
data[names=='bob']

array([[-0.97008236,  0.86985823,  0.10699726, -0.89757453]])

In [159]:
# array(1.865.., -0.17893...)
data[names=='bob',2:]

array([[ 0.10699726, -0.89757453]])

In [160]:
data[~(names=='bob')]

array([[ 1.17469316, -0.15631129, -0.47882262, -0.48743776],
       [ 1.86861288,  1.37530394,  0.30821481, -0.62066787],
       [ 0.10844734,  0.57141365,  1.596644  ,  1.7138495 ],
       [ 1.01203413, -0.12030664, -1.11519312,  0.33520322],
       [-1.02232956,  0.60114853, -1.2055723 , -0.00310021],
       [ 0.94850782,  1.59295635, -1.58483102,  0.31055118]])

In [161]:
data[~(names=='bob'),:2]

array([[ 1.17469316, -0.15631129],
       [ 1.86861288,  1.37530394],
       [ 0.10844734,  0.57141365],
       [ 1.01203413, -0.12030664],
       [-1.02232956,  0.60114853],
       [ 0.94850782,  1.59295635]])

In [162]:
data[names=='bob',3]

array([-0.89757453])

In [163]:
data[~(names=='bob'),3]

array([-0.48743776, -0.62066787,  1.7138495 ,  0.33520322, -0.00310021,
        0.31055118])

In [164]:
cond = names == 'bob'

In [165]:
data[cond]

array([[-0.97008236,  0.86985823,  0.10699726, -0.89757453]])

In [166]:
data[~cond]

array([[ 1.17469316, -0.15631129, -0.47882262, -0.48743776],
       [ 1.86861288,  1.37530394,  0.30821481, -0.62066787],
       [ 0.10844734,  0.57141365,  1.596644  ,  1.7138495 ],
       [ 1.01203413, -0.12030664, -1.11519312,  0.33520322],
       [-1.02232956,  0.60114853, -1.2055723 , -0.00310021],
       [ 0.94850782,  1.59295635, -1.58483102,  0.31055118]])

In [167]:
mask = (names == 'bob') | (names == 'ross')

In [168]:
data[mask]

array([[-0.97008236,  0.86985823,  0.10699726, -0.89757453],
       [-1.02232956,  0.60114853, -1.2055723 , -0.00310021]])

In [169]:
data[data<0]=69


In [170]:
data

array([[ 69.        ,   0.86985823,   0.10699726,  69.        ],
       [  1.17469316,  69.        ,  69.        ,  69.        ],
       [  1.86861288,   1.37530394,   0.30821481,  69.        ],
       [  0.10844734,   0.57141365,   1.596644  ,   1.7138495 ],
       [  1.01203413,  69.        ,  69.        ,   0.33520322],
       [ 69.        ,   0.60114853,  69.        ,  69.        ],
       [  0.94850782,   1.59295635,  69.        ,   0.31055118]])

In [171]:
data[names == 'bob'] = 6

In [172]:
data


array([[  6.        ,   6.        ,   6.        ,   6.        ],
       [  1.17469316,  69.        ,  69.        ,  69.        ],
       [  1.86861288,   1.37530394,   0.30821481,  69.        ],
       [  0.10844734,   0.57141365,   1.596644  ,   1.7138495 ],
       [  1.01203413,  69.        ,  69.        ,   0.33520322],
       [ 69.        ,   0.60114853,  69.        ,  69.        ],
       [  0.94850782,   1.59295635,  69.        ,   0.31055118]])

# Fancy Indexing

In [173]:
nArray = np.empty([4,8])

In [174]:
nArray
# type(nArray)
# numpy.ndarray


array([[  4.65473167e-310,   6.93197028e-310,   4.65472987e-310,
          6.93192416e-310,   6.93192416e-310,   6.93192416e-310,
          6.93192416e-310,   6.93192416e-310],
       [  6.93192416e-310,   6.93192416e-310,   6.93192416e-310,
          4.65472987e-310,   6.93192416e-310,   6.93192416e-310,
          6.93192416e-310,   6.93192416e-310],
       [  6.93192416e-310,   6.93192416e-310,   6.93192416e-310,
          6.93192416e-310,   6.93192416e-310,   6.93192416e-310,
          6.93192416e-310,   6.93192416e-310],
       [  6.93192416e-310,   6.93192416e-310,   6.93192416e-310,
          6.93192416e-310,   6.93192416e-310,   6.93192416e-310,
          6.93192416e-310,   6.93192416e-310]])

In [175]:
nArray=np.empty((4,8))

In [176]:
nArray
# type(nArray)
# numpy.ndarray

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [177]:
for i in range(len(nArray)):
    nArray[i]=i+1

In [178]:
nArray

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.]])

In [179]:
nArray[[2,3],[3,2]]

array([ 3.,  4.])

In [180]:
nArray[[2,3]]

array([[ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.]])

In [181]:
copyArray = nArray

In [182]:
copyArray +1


array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.]])

In [183]:
nArray

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.]])

In [184]:
nArray = np.arange(15).reshape((3,5))

In [185]:
nArray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [186]:
nArray = np.arange(15).reshape((1,15))

In [187]:
nArray


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [188]:
nArray.T

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [189]:
nArray[0][2]

2

In [190]:
nArray[0][14]

14

In [191]:
np.dot(nArray.T,nArray)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14],
       [  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
         26,  28],
       [  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
         39,  42],
       [  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
         52,  56],
       [  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
         65,  70],
       [  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,
         78,  84],
       [  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,
         91,  98],
       [  0,   8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96,
        104, 112],
       [  0,   9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108,
        117, 126],
       [  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       

In [192]:
#  Mathematical and Statistical Methods

In [193]:
arr = np.random.randn(4,6)

In [194]:
arr

array([[-0.2483183 ,  0.14020392,  0.77604745, -1.36895279,  1.27008612,
         0.48738729],
       [ 1.10012052,  1.71957652, -0.00376456, -0.81416502, -1.13429598,
         0.80031544],
       [ 0.47902634, -1.73861822, -1.49410609, -0.7242777 , -1.20198735,
         0.78219635],
       [ 0.11509055,  0.26379496, -0.25568581, -0.71179934,  0.11513576,
         0.94136626]])

In [195]:
arr.mean()

-0.029400986301919434

In [196]:
arr.mean(axis=1)

array([ 0.17607562,  0.27796449, -0.64962778,  0.07798373])

In [197]:
arr.mean(axis=0)

array([ 0.36147978,  0.0962393 , -0.24437725, -0.90479871, -0.23776536,
        0.75281634])

In [198]:
arr.sum()

-0.7056236712460664

In [199]:
arr.sum(axis=0)

array([ 1.44591911,  0.38495718, -0.97750901, -3.61919485, -0.95106145,
        3.01126534])

In [200]:
arr.sum(axis=1)

array([ 1.0564537 ,  1.66778692, -3.89776668,  0.46790238])

In [212]:
names


array(['bob', 'sob', 'leela', 'majnu', 'apsara', 'ross', 'leo'], 
      dtype='<U6')

In [214]:
names.put(1,'bob')

In [215]:
names

array(['bob', 'bob', 'leela', 'majnu', 'apsara', 'ross', 'leo'], 
      dtype='<U6')

In [216]:
np.unique(names)

array(['apsara', 'bob', 'leela', 'leo', 'majnu', 'ross'], 
      dtype='<U6')